"""create roles_and_permissions table

Revision ID: 7ab0bbb0fcc5
Revises: e9899ba49fa2
Create Date: 2025-05-13 17:20:04.433113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ab0bbb0fcc5'
down_revision: Union[str, None] = 'e9899ba49fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_chatbot_leads_id', table_name='chatbot_leads')
    op.drop_table('chatbot_leads')
    op.drop_index('ix_chat_bots_faqs_id', table_name='chat_bots_faqs')
    op.drop_table('chat_bots_faqs')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_bots_id', table_name='chat_bots')
    op.drop_table('chat_bots')
    op.drop_index('ix_subscription_plans_id', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('ix_chat_bots_doc_links_id', table_name='chat_bots_doc_links')
    op.drop_table('chat_bots_doc_links')
    op.drop_table('chat_settings')
    op.drop_index('ix_chat_sessions_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('users_old')
    op.drop_index('_bot_type_uc', table_name='instruction_prompts')
    op.drop_index('ix_instruction_prompts_id', table_name='instruction_prompts')
    op.drop_table('instruction_prompts')
    op.drop_index('ix_slack_installations_id', table_name='slack_installations')
    op.drop_index('team_id', table_name='slack_installations')
    op.drop_table('slack_installations')
    op.drop_index('ix_bot_products_id', table_name='bot_products')
    op.drop_table('bot_products')
    op.drop_index('ix_chat_total_tokens_id', table_name='chat_total_tokens')
    op.drop_table('chat_total_tokens')
    op.drop_index('ix_token_bots_id', table_name='token_bots')
    op.drop_table('token_bots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_bots',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pricing', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token_limits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_token_bots_id', 'token_bots', ['id'], unique=False)
    op.create_table('chat_total_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_token', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('token_consumed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plan', mysql.ENUM('basic', 'pro', 'ent'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], name='chat_total_tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_total_tokens_id', 'chat_total_tokens', ['id'], unique=False)
    op.create_table('bot_products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_bot_products_id', 'bot_products', ['id'], unique=False)
    op.create_table('slack_installations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bot_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('team_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('team_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bot_user_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('authed_user_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('installed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('team_id', 'slack_installations', ['team_id'], unique=True)
    op.create_index('ix_slack_installations_id', 'slack_installations', ['id'], unique=False)
    op.create_table('instruction_prompts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prompt', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['chat_bots.id'], name='instruction_prompts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_instruction_prompts_id', 'instruction_prompts', ['id'], unique=False)
    op.create_index('_bot_type_uc', 'instruction_prompts', ['bot_id', 'type'], unique=True)
    op.create_table('users_old',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fullName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('isRestricted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isMFA', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('googleId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebookId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('picture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('plan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tokenUsed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_active', mysql.DATETIME(), nullable=True),
    sa.Column('role_permissions', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fullName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('isRestricted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isMFA', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('googleId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebookId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('picture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('plan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tokenUsed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_active', mysql.DATETIME(), nullable=True),
    sa.Column('role_permissions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('platform', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], name='chat_sessions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_sessions_id', 'chat_sessions', ['id'], unique=False)
    op.create_table('chat_settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title_value', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('title_is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('welcome_message_value', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('welcome_message_is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('suggestions_value', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('suggestions_is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('placeholder_value', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('placeholder_is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lead_collection', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('chat_window_bg', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('send_button_color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('chat_icon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('chat_icon_color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('user_message_bg', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dots_color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('message_bg', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('live_message_bg', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('name_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_name_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('required_name_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('mail_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_mail_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('required_mail_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('phone_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_phone_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('required_phone_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('message_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('is_message_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('required_message_lead_gen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('submission_message_heading_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('sumbission_message_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('submit_text_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('submit_button_color_lead_gen', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chat_bots_doc_links',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('chatbot_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('train_from', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('target_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('document_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('text_content', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('chars', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], name='chat_bots_doc_links_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_bots_doc_links_id', 'chat_bots_doc_links', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pricing', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token_limits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('features', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('users_active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subscription_plans_id', 'subscription_plans', ['id'], unique=False)
    op.create_table('chat_bots',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('chatbot_name', mysql.TEXT(), nullable=True),
    sa.Column('train_from', mysql.TEXT(), nullable=True),
    sa.Column('target_link', mysql.TEXT(), nullable=True),
    sa.Column('document_link', mysql.TEXT(), nullable=True),
    sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('text_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('Creativity', mysql.INTEGER(display_width=3, unsigned=True, zerofill=True), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('domains', mysql.TEXT(), nullable=True),
    sa.Column('limit_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('every_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_bots_id', 'chat_bots', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sender', mysql.ENUM('user', 'bot'), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_sessions.id'], name='chat_messages_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_table('chat_bots_faqs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('answer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_old.id'], name='chat_bots_faqs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_bots_faqs_id', 'chat_bots_faqs', ['id'], unique=False)
    op.create_table('chatbot_leads',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('chat_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chatbot_leads_id', 'chatbot_leads', ['id'], unique=False)
    # ### end Alembic commands ###
